package com.doctoolkit.service;
import net.sourceforge.tess4j.*; import org.apache.pdfbox.multipdf.*; import org.apache.pdfbox.pdmodel.*; import org.apache.pdfbox.pdmodel.font.PDType1Font; import org.apache.pdfbox.pdmodel.PDPageContentStream; import org.apache.poi.xwpf.extractor.XWPFWordExtractor; import org.apache.poi.xwpf.usermodel.XWPFDocument; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.nio.file.*; import java.util.*; import java.util.zip.*;
@Service public class FileConversionService { @Value("${doctoolkit.temp-dir}") Path tempDir; @Value("${doctoolkit.tesseract.datapath}") String tessdata;
 public Path convert(MultipartFile file,String targetFormat)throws Exception{Path in=save(file); String text=extractText(in,file.getOriginalFilename()); Path out=Path.of(temp("converted.")+targetFormat); switch(targetFormat.toLowerCase()){case "txt", "html", "epub" -> Files.writeString(out, "html".equals(targetFormat)?"<pre>"+text.replace("&","&amp;").replace("<","&lt;")+"</pre>":text); case "pdf" -> writePdf(out,text); default -> Files.copy(in,out,StandardCopyOption.REPLACE_EXISTING);} Files.deleteIfExists(in); return out;}
 public Path compress(MultipartFile file)throws Exception{Path in=save(file), out=Path.of(temp("compressed.")+"pdf"); try(PDDocument d=PDDocument.load(in.toFile())){d.setAllSecurityToBeRemoved(true); d.save(out.toFile());} Files.deleteIfExists(in); return out;}
 public Path merge(List<MultipartFile> files)throws Exception{Path out=Path.of(temp("merged.")+"pdf"); PDFMergerUtility m=new PDFMergerUtility(); List<Path> ins=new ArrayList<>(); for(MultipartFile f:files){Path p=save(f); ins.add(p); m.addSource(p.toFile());} m.setDestinationFileName(out.toString()); m.mergeDocuments(null); for(Path p:ins)Files.deleteIfExists(p); return out;}
 public Path split(MultipartFile file,String ranges)throws Exception{Path in=save(file), zip=Path.of(temp("split.")+"zip"); try(PDDocument d=PDDocument.load(in.toFile()); ZipOutputStream zos=new ZipOutputStream(Files.newOutputStream(zip))){int i=1; for(String r:ranges.split(",")){String[] parts=r.trim().split("-"); int start=Integer.parseInt(parts[0]); int end=parts.length>1?Integer.parseInt(parts[1]):start; try(PDDocument part=new PDDocument()){for(int p=start;p<=end;p++) part.importPage(d.getPage(p-1)); ByteArrayOutputStream bos=new ByteArrayOutputStream(); part.save(bos); zos.putNextEntry(new ZipEntry("split-"+(i++)+".pdf")); zos.write(bos.toByteArray()); zos.closeEntry();}}} Files.deleteIfExists(in); return zip;}
 public Path ocr(MultipartFile file,String langs)throws Exception{Path in=save(file), out=Path.of(temp("ocr.")+"txt"); Tesseract t=new Tesseract(); t.setDatapath(tessdata); t.setLanguage((langs==null||langs.isBlank())?"eng+hin+mar":langs); Files.writeString(out,t.doOCR(in.toFile())); Files.deleteIfExists(in); return out;}
 private Path save(MultipartFile f)throws IOException{Files.createDirectories(tempDir); Path p=Path.of(temp("upload.")+(Optional.ofNullable(f.getOriginalFilename()).orElse("bin").replaceAll(".*\\.",""))); f.transferTo(p); return p;} private String temp(String prefix)throws IOException{return Files.createTempFile(tempDir,prefix,"").toString();}
 private String extractText(Path in,String name)throws Exception{String n=name==null?"":name.toLowerCase(); if(n.endsWith(".docx")){try(XWPFDocument d=new XWPFDocument(Files.newInputStream(in)); XWPFWordExtractor e=new XWPFWordExtractor(d)){return e.getText();}} if(n.endsWith(".pdf")){try(PDDocument d=PDDocument.load(in.toFile())){return new org.apache.pdfbox.text.PDFTextStripper().getText(d);}} return Files.readString(in);}
 private void writePdf(Path out,String text)throws IOException{try(PDDocument d=new PDDocument()){PDPage page=new PDPage(); d.addPage(page); try(PDPageContentStream cs=new PDPageContentStream(d,page)){cs.beginText(); cs.setFont(PDType1Font.HELVETICA,12); cs.newLineAtOffset(50,750); for(String line:text.split("\\R")){cs.showText(line.replaceAll("[^\\x20-\\x7E]","?")); cs.newLineAtOffset(0,-15);} cs.endText();} d.save(out.toFile());}}
}
