package com.example.fileconverter.utils

import android.content.ContentResolver
import android.content.ContentValues
import android.content.Context
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream

object FileHelper {

    /**
     * Copies picked content URI into app cache for easier read/seek access.
     */
    fun copyUriToCache(context: Context, uri: Uri, extension: String): File {
        val cacheFile = File.createTempFile("input_", ".$extension", context.cacheDir)
        context.contentResolver.openInputStream(uri).use { input ->
            FileOutputStream(cacheFile).use { output ->
                if (input == null) throw IOException("Unable to read selected file")
                input.copyTo(output)
            }
        }
        return cacheFile
    }

    /**
     * Saves generated bytes to Downloads/FileConverter and returns absolute path.
     */
    fun saveBytesToDownloads(
        context: Context,
        fileName: String,
        mimeType: String,
        bytes: ByteArray
    ): String {
        val resolver = context.contentResolver
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            saveToMediaStore(resolver, fileName, mimeType, bytes)
        } else {
            saveLegacy(fileName, bytes)
        }
    }

    private fun saveToMediaStore(
        resolver: ContentResolver,
        fileName: String,
        mimeType: String,
        bytes: ByteArray
    ): String {
        val contentValues = ContentValues().apply {
            put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
            put(MediaStore.MediaColumns.MIME_TYPE, mimeType)
            put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/FileConverter")
        }
        val collection = MediaStore.Downloads.EXTERNAL_CONTENT_URI
        val itemUri = resolver.insert(collection, contentValues)
            ?: throw IOException("Failed to create destination file")
        resolver.openOutputStream(itemUri).use { output ->
            if (output == null) throw IOException("Cannot open output stream")
            output.write(bytes)
        }
        return itemUri.toString()
    }

    @Suppress("DEPRECATION")
    private fun saveLegacy(fileName: String, bytes: ByteArray): String {
        val folder = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "FileConverter")
        if (!folder.exists() && !folder.mkdirs()) {
            throw IOException("Unable to create Downloads/FileConverter")
        }
        val outputFile = File(folder, fileName)
        FileOutputStream(outputFile).use { it.write(bytes) }
        return outputFile.absolutePath
    }

    fun readAllBytes(context: Context, uri: Uri): ByteArray {
        val input: InputStream = context.contentResolver.openInputStream(uri)
            ?: throw IOException("Cannot open selected file")
        return input.use { it.readBytes() }
    }

    fun uriFileName(context: Context, uri: Uri): String {
        val projection = arrayOf(MediaStore.MediaColumns.DISPLAY_NAME)
        context.contentResolver.query(uri, projection, null, null, null)?.use { cursor ->
            val idx = cursor.getColumnIndex(MediaStore.MediaColumns.DISPLAY_NAME)
            if (idx >= 0 && cursor.moveToFirst()) return cursor.getString(idx)
        }
        return "selected_file"
    }
}
